######################
#### AUTOMATIONS #####
######################
## automations.yaml ##
######################

##### Switch the lights on as the sun gets dim - Trigger caused by a timed offset before sunset:
  # trigger:
    # platform: sun
    # event: sunset
    # offset: "-00:45:00"
  # condition:
    # condition: state
    # entity_id: group.all_devices
    # state: home
  # action:
    # service: homeassistant.turn_on
    # entity_id: group.living_room_lights

#### Switch the lights on as the sun gets dim - Trigger caused by elevation of the sun:
- alias: 'Turn a few lights on when the sun gets dim'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
  # trigger: # DEBUG - trigger event via boolean switch
    # - platform: state
      # entity_id: input_boolean.day_night
      # to: 'on'
  # condition:
    # - condition: template
      # value_template: "{% if is_state('input_boolean.home_away', 'on') %}true{% endif %}"
  action:
    - service: scene.turn_on
      entity_id: scene.katzenbeleuchtung
    - service: notify.home_assistant1
      data:
        message: "Katzenbeleuchtung EINGESCHALTET!"

#### Switch off 'Katzenbeleuchtung' at 23:00 if its mon - thu + sun
- alias: 'Katzenbeleuchtung abschalten'
  trigger:
    platform: time
    at: "23:00:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - sun
  action:
    service: light.turn_off
    entity_id: light.flur
    # data: # if Transisition will be possible with IKEA Tradfri bulbs uncomment the next lines
      # # 900 seconds = 15 minutes
      # transition: 900

#### Switch off 'Katzenbeleuchtung' at 00:30 if its weekend
- alias: 'Katzenbeleuchtung abschalten'
  trigger:
    platform: time
    at: "00:30:00"
  condition:
    condition: time
    weekday:
      - fri
      - sat
  action:
    service: light.turn_off
    entity_id: light.flur
    # data: # if Transisition will be possible with IKEA Tradfri bulbs uncomment the next lines
      # # 900 seconds = 15 minutes
      # transition: 900

# script:
  # hello_world:
    # sequence:
    # - condition: and
      # conditions:
        # - condition: numeric_state
          # entity_id: sensor.temperature
          # below: 25
        # - condition: sun
          # after: sunrise
    # - service: homeassistant.turn_on
      # entity_id: group.living_room


# Example for further dimming of lights
# - alias: 'Turn more lights on as the sun gets dimmer'
  # trigger:
    # platform: numeric_state
    # entity_id: sun.sun
    # value_template: '{{ state.attributes.elevation }}'
    # below: 1.5
  # action:
    # service: scene.turn_on
    # entity_id: scene.more_lights

# Example for multiple triggers
  # trigger:
      # # first trigger
    # - platform: time
      # minutes: 5
      # seconds: 00
      # # our second trigger is the sunset
    # - platform: sun
      # event: sunset

- alias: Notify at night switch
  trigger:
    platform: state
    entity_id: input_boolean.day_night
    to: 'on'
  action:
    service: notify.home_assistant1
    data:
      message: "Something happened at home!"